// <auto-generated />
namespace OnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _mig10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_mig10));
        
        string IMigrationMetadata.Id
        {
            get { return "202303272021508__mig10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
